"""add_prescription_refill_tracking_fields

Revision ID: 346fbca7349f
Revises: add_regimens
Create Date: 2025-11-18 04:39:15.893421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346fbca7349f'
down_revision = 'add_regimens'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('medications', sa.Column('refills_total', sa.Integer(), nullable=True))
    op.add_column('medications', sa.Column('refills_used', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('medications', sa.Column('days_supply', sa.Integer(), nullable=True))
    op.drop_index('ix_third_parties_user_id', table_name='third_parties')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_third_parties_user_id', 'third_parties', ['user_id'], unique=False)
    op.drop_column('medications', 'days_supply')
    op.drop_column('medications', 'refills_used')
    op.drop_column('medications', 'refills_total')
    op.drop_column('medications', 'quantity')
    # ### end Alembic commands ###
