"""add_symptom_images_table

Revision ID: 883cd672b448
Revises: 346fbca7349f
Create Date: 2025-11-18 14:09:52.267516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883cd672b448'
down_revision = '346fbca7349f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symptom_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptom_tracking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_images_id'), 'symptom_images', ['id'], unique=False)
    op.create_index(op.f('ix_symptom_images_symptom_id'), 'symptom_images', ['symptom_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symptom_images_symptom_id'), table_name='symptom_images')
    op.drop_index(op.f('ix_symptom_images_id'), table_name='symptom_images')
    op.drop_table('symptom_images')
    # ### end Alembic commands ###
